#include<stdlib.h>
#include<stdio.h>
#include"ref.h"

//BSD checksum on char* and int*
static int csum1(char*p,int nr); 
static int bsum(int*x,int n){return csum1((char*)x,n*4);}

/* csum1 - the BSD checksum algorithm.   rotate and add
 * derived from the BSD source at https://svnweb.freebsd.org/base/stable/9/usr.bin/cksum/sum1.c
 */
static int csum1(char*p,int nr) {
 int lcrc=0;
 for (;nr--;p++) {
  if (lcrc & 1)           //if low bit is one
    lcrc |= 0x10000;      //get ready to shift it into bit 15
  lcrc = ((lcrc >> 1) + *p) & 0xffff;
 }
 return lcrc;
}

//roll: set x to n random ints
static int*roll(int*x,int n) {
 int*e=x+n,*y=x;
 while(y<e)
  *y++=prng();
 return x;
}

/*
 *  tcheck
 */
int tcheck(int s,int n) { // s is seed, x is array space, 2^n is number of randoms
 n=1<<n;
 int*x=malloc(n*4);
 seed(s);
 int r=bsum(roll(x,n),n);
 free(x);
 return r;
}
/*
 * tsort
 */
void quicksort(int*x, int n) {
  if (n < 2) return;
  int pivot = x[n/2];
  int i, j;
  for (i = 0, j = n - 1; ; i++, j--) {
    while (x[i] < pivot) i++;
    while (x[j] > pivot) j--;
    if (i >= j) break;
    int temp = x[i];
    x[i]     = x[j];
    x[j]     = temp;
  }
  quicksort(x, i);
  quicksort(x + i, n - i);
}
int tsort(int s,int n) {
  n=1<<n;
  int*x=malloc(n*4);
  seed(s);
  quicksort(roll(x,n),n);
  int r=bsum(x,n);
  free(x);
  return r;
}
/*
 * tshuf
 */
static int*seq(int*a,int n) {
 int i=0;
 n=1<<n;
 while(i<n)
  a[i++]=i;
 return a;
}
#define max(x,y)    (x<y?y:x)
static int*shuffle(int*a,int n) {
 int i=n-1;
 while(i>0)
 {int r=prng();
  int j=max(r,-r)%(i+1);
  int aj=a[j];a[j]=a[i];a[i]=aj;
  i--;
 }
 return a;
}
int tshuf(int s,int n) {
  n=1<<n;
  int*x=malloc(n*4);
  seed(s);
  int r=bsum(shuffle(roll(x,n),n),n);
  free(x);
  return r;
}

/* argv generated by abench
 * has form 
 *   prog test n seed
 */
#define casei(i,tfun) case i: printf("%d\n",tfun(s,n)); return 0;
int main(int argc, char**argv) {
  if(argc!=4)
     return 11;
  int t=atoi(argv[1]);
  int n=atoi(argv[2]);
  int s=atoi(argv[3]);
  switch(t) {
    casei(0,tcheck)
    casei(1,tsort)
    casei(2,tshuf)
    default: return 12;
  }
  return 0;
}
