#include<iostream>
#include<vector>
#include<cstdlib>
#include<ref.h>

typedef std::vector<int>A;
//BSD checksum on char* and int*
static int csum1 (char *p, int nr);
static int
bsum (const A&x)
{
  return csum1((char *)&x[0],x.size()*4);
}
static int
csum1 (char *p, int nr)
{
  int lcrc = 0;
  for (; nr--; p++) {
    if (lcrc & 1)		//if low bit is one
      lcrc |= 0x10000;		//get ready to shift it into bit 15
    lcrc = ((lcrc >> 1) + *p) & 0xffff;
  }
  return lcrc;
}

//roll: set x to n random ints
static A&
roll (A&x)
{
  A::iterator e = x.end(),y=x.begin();
  while (y < e)
    *y++ = prng ();
  return x;
}

/*
 *  tcheck
 */
int
tcheck (int s,int n)
{				// s is seed, x is array space, 2^n is number of randoms
  n = 1 << n;
  A*x = new A(n*4);
  seed (s);
  int r = bsum (roll(*x));
  delete x;
  return r;
}

/*
 * tsort
 */
#include <iterator>
#include <algorithm> // for std::partition
#include <functional> // for std::less
 
template<typename RandomAccessIterator,
         typename Order>
 void quicksort(RandomAccessIterator first, RandomAccessIterator last, Order order)
{
  if (last - first > 1)
  {
    RandomAccessIterator split = std::partition(first+1, last, std::bind2nd(order, *first));
    std::iter_swap(first, split-1);
    quicksort(first, split-1, order);
    quicksort(split, last, order);
  }
}
 
template<typename RandomAccessIterator>
 void quicksort(RandomAccessIterator first, RandomAccessIterator last)
{
  quicksort(first, last, std::less<typename std::iterator_traits<RandomAccessIterator>::value_type>());
}

int
tsort (int s, int n)
{
  n = 1 << n;
  A*x = new A(n*4);
  seed (s);
  roll (*x);
  quicksort (x->begin(),x->end());
  int r = bsum (*x);
  delete x;
  return r;
}

/*
 * tshuf
 */
static int *
seq (int *a, int n)
{
  int i = 0;
  n = 1 << n;
  while (i < n)
    a[i++] = i;
  return a;
}

#define max(x,y)    (x<y?y:x)
static A&
shuffle (A&a)
{
  int i = a.size() - 1;
  while (i > 0) {
    int r = prng ();
    int j = max (r, -r) % (i + 1);
    int aj = a[j];
    a[j] = a[i];
    a[i] = aj;
    i--;
  }
  return a;
}

int
tshuf (int s, int n)
{
  n = 1 << n;
  A*x = new A(n*4);
  seed (s);
  int r = bsum (shuffle (roll (*x)));
  delete x;
  return r;
}

/* argv generated by run.py
 * has form 
 *   ./ref test n seed
 */
#define casei(i,tfun) case i: std::cout<<tfun(s,n)<<std::endl; return 0
int
main (int argc, char **argv)
{
  if (argc != 4)
    return 11;
  int t = atoi (argv[1]);
  int n = atoi (argv[2]);
  int s = atoi (argv[3]);
  switch (t) {
    casei (0, tcheck);
    casei (1, tsort);
    casei (2, tshuf);
  default:
    return 12;
  }
  return 0;
}
